name: "Bug Report"
description: "오류/장애/오동작을 제보합니다."
title: "[Bug] "
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        문제를 빠르게 재현할 수 있도록 아래 항목을 가능한 구체적으로 작성해주세요.
  - type: dropdown
    id: area
    attributes:
      label: 영향 영역
      description: 문제가 발생한 영역을 선택하세요.
      options:
        - Frontend (Web UI)
        - BFF/API
        - Firebase Authentication
        - Firestore
        - Automation Script (scripts/*)
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: 사용자 영향
      description: 누가 어떤 업무를 못하게 되었는지 적어주세요.
      placeholder: 예) 재무 담당자가 거래 승인 화면에서 저장을 못함
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 재현 절차
      description: 순서대로 번호를 붙여 작성해주세요.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 기대 동작
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 실제 동작
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: 실행 환경
      description: 브라우저/OS/배포환경(Production, Preview, Local) 등
      placeholder: Chrome 131, macOS 15, Vercel Production
  - type: textarea
    id: evidence
    attributes:
      label: 로그/스크린샷/에러 메시지
      description: 민감정보(키/토큰/개인정보)는 제거하고 첨부해주세요.
      placeholder: 에러 원문, 콘솔 로그, API 응답 등
  - type: checkboxes
    id: checks
    attributes:
      label: 사전 확인
      options:
        - label: 중복 이슈를 검색했습니다.
          required: true
        - label: 민감정보(.env, key, token)를 포함하지 않았습니다.
          required: true

