import type { FileAttachment, Project, ProjectRequest, ProjectRequestPayload } from '../data/types';

const contractDocument: FileAttachment = {
  path: 'dev-harness/project-registration/e2e-contract.pdf',
  name: 'E2E_프로젝트_계약서.pdf',
  downloadURL: 'data:application/pdf;base64,JVBERi0xLjQKMSAwIG9iago8PC9UeXBlL0NhdGFsb2cvUGFnZXMgMiAwIFI+PgplbmRvYmoKMiAwIG9iago8PC9UeXBlL1BhZ2VzL0tpZHNbMyAwIFJdL0NvdW50IDE+PgplbmRvYmoKMyAwIG9iago8PC9UeXBlL1BhZ2UvUGFyZW50IDIgMCBSL01lZGlhQm94WzAgMCAxIDE+Pj4KZW5kb2JqCnRyYWlsZXIKPDwvUm9vdCAxIDAgUj4+CiUlRU9G',
  size: 412,
  contentType: 'application/pdf',
  uploadedAt: '2026-07-03T09:00:00+09:00',
};

const payload: ProjectRequestPayload = {
  name: 'E2E 결재선 검증 프로젝트',
  officialContractName: 'E2E 결재선 검증 프로젝트 계약',
  type: 'A1',
  status: 'CONTRACT_PENDING',
  phase: 'PROSPECT',
  description: '로컬 Playwright에서 결재선과 의견 이력을 검증하는 전용 문서입니다.',
  clientOrg: 'MYSC 테스트 발주처',
  department: 'CIC2',
  groupwareName: 'E2E 결재선 검증',
  currency: 'KRW',
  contractAmount: 120_000_000,
  salesVatAmount: 10_909_091,
  totalRevenueAmount: 98_000_000,
  supportAmount: 0,
  contractStart: '2026-08-01',
  contractEnd: '2026-12-31',
  contractType: '계약서(날인)',
  settlementType: 'TYPE1',
  basis: '공급가액',
  accountType: 'DEDICATED',
  paymentPlan: { contract: 84_000_000, interim: 0, final: 36_000_000 },
  paymentPlanDesc: '선금 70%, 잔금 30%',
  settlementGuide: '증빙 기준에 맞춰 월별 정산합니다.',
  projectPurpose: '결재 문서 UI 회귀 검증',
  registeredById: 'e2e-pm',
  registeredByName: '테스트 PM',
  registeredByEmail: 'e2e.pm@mysc.co.kr',
  executiveApproverId: 'e2e-head',
  executiveApproverName: '테스트 조직장',
  executiveApproverEmail: 'e2e.head@mysc.co.kr',
  managerId: 'e2e-pm',
  managerName: '테스트 PM',
  teamName: 'CIC2 1팀',
  teamMembers: '테스트 PM',
  participantCondition: '해당 없음',
  note: '기안 메모: 계약 범위와 예산을 검토해 주세요.',
  contractDocument,
};

const project: Project = {
  id: 'dev-e2e-migration-audit',
  slug: 'dev-e2e-migration-audit',
  orgId: 'mysc',
  cic: 'CIC2',
  registrationSource: 'pm_portal',
  registeredById: payload.registeredById,
  registeredByName: payload.registeredByName,
  registeredByEmail: payload.registeredByEmail,
  executiveApproverId: payload.executiveApproverId,
  executiveApproverName: payload.executiveApproverName,
  executiveApproverEmail: payload.executiveApproverEmail,
  registeredAt: '2026-07-01T09:00:00+09:00',
  executiveReviewStatus: 'PENDING',
  executiveReviewComment: null,
  executiveReviewHistory: [
    {
      status: 'PENDING',
      previousStatus: null,
      reviewedAt: '2026-07-01T09:00:00+09:00',
      reviewedById: 'e2e-pm',
      reviewedByName: '테스트 PM',
      reviewComment: '초기 제출 메모: 계약 범위 확인 부탁드립니다.',
    },
    {
      status: 'REVISION_REJECTED',
      previousStatus: 'PENDING',
      reviewedAt: '2026-07-02T10:00:00+09:00',
      reviewedById: 'e2e-head',
      reviewedByName: '테스트 조직장',
      reviewComment: '반려 메모: 계약기간을 보완해 주세요.',
    },
    {
      status: 'PENDING',
      previousStatus: 'REVISION_REJECTED',
      reviewedAt: '2026-07-03T09:00:00+09:00',
      reviewedById: 'e2e-pm',
      reviewedByName: '테스트 PM',
      reviewComment: '재제출 메모: 계약기간을 보완했습니다.',
    },
  ],
  name: payload.name,
  shortName: payload.name,
  officialContractName: payload.officialContractName,
  status: 'CONTRACT_PENDING',
  type: payload.type,
  phase: 'PROSPECT',
  currency: 'KRW',
  contractAmount: payload.contractAmount,
  contractStart: payload.contractStart,
  contractEnd: payload.contractEnd,
  settlementType: payload.settlementType,
  basis: payload.basis,
  accountType: payload.accountType,
  paymentPlan: payload.paymentPlan,
  paymentPlanDesc: payload.paymentPlanDesc,
  clientOrg: payload.clientOrg,
  groupwareName: payload.groupwareName || '',
  participantCondition: payload.participantCondition,
  note: payload.note,
  contractType: payload.contractType || '',
  projectPurpose: payload.projectPurpose,
  totalRevenueAmount: payload.totalRevenueAmount,
  salesVatAmount: payload.salesVatAmount,
  contractDocument,
  department: payload.department,
  teamName: payload.teamName,
  managerId: payload.managerId || '',
  managerName: payload.managerName,
  budgetCurrentYear: payload.contractAmount,
  taxInvoiceAmount: 0,
  profitRate: 0.18,
  profitAmount: 21_600_000,
  isSettled: false,
  finalPaymentNote: '잔금 수령 전',
  confirmerName: '',
  lastCheckedAt: '2026-07-03T09:00:00+09:00',
  cashflowDiffNote: '',
  description: payload.description,
  createdAt: '2026-07-01T09:00:00+09:00',
  updatedAt: '2026-07-03T09:00:00+09:00',
};

export const DEV_MIGRATION_AUDIT_E2E_FIXTURE: { project: Project; request: ProjectRequest } = {
  project,
  request: {
    id: 'dev-e2e-migration-request',
    tenantId: 'mysc',
    requestKind: 'REGISTRATION',
    targetProjectId: project.id,
    requestVersion: 3,
    status: 'PENDING',
    payload,
    humanSummary: '초기 등록 후 보완하여 다시 제출한 프로젝트입니다.',
    requestedBy: 'e2e-pm',
    requestedByName: '테스트 PM',
    requestedByEmail: 'e2e.pm@mysc.co.kr',
    requestedAt: '2026-07-03T09:00:00+09:00',
    createdAt: '2026-07-01T09:00:00+09:00',
    updatedAt: '2026-07-03T09:00:00+09:00',
  },
};
