#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

REGION="${REGION:-asia-northeast3}"
SERVICE_NAME="${SERVICE_NAME:-mysc-bff}"
IMAGE_TAG="${IMAGE_TAG:-$(date +%Y%m%d-%H%M%S)}"
PROJECT_ID="${FIREBASE_PROJECT_ID:-${GOOGLE_CLOUD_PROJECT:-}}"
BFF_DEPLOY_ENV="${BFF_DEPLOY_ENV:-stage}"
BFF_ALLOWED_ORIGINS="${BFF_ALLOWED_ORIGINS:-http://127.0.0.1:5173,http://localhost:5173}"
BFF_WORKERS_ENABLED="${BFF_WORKERS_ENABLED:-false}"
BFF_SCHEDULER_OWNER="${BFF_SCHEDULER_OWNER:-disabled}"
BFF_OUTBOX_BATCH="${BFF_OUTBOX_BATCH:-50}"
BFF_OUTBOX_MAX_ATTEMPTS="${BFF_OUTBOX_MAX_ATTEMPTS:-8}"
PII_MODE="${PII_MODE:-off}"
PII_KMS_KEYS="${PII_KMS_KEYS:-}"
PII_KMS_CURRENT_KEY="${PII_KMS_CURRENT_KEY:-}"
BFF_SERVERLESS_VPC_CONNECTOR="${BFF_SERVERLESS_VPC_CONNECTOR:-}"
JVM_WEEKLY_API_BASE_URL="${JVM_WEEKLY_API_BASE_URL:-}"
JVM_WEEKLY_API_ID_TOKEN_AUDIENCE="${JVM_WEEKLY_API_ID_TOKEN_AUDIENCE:-}"
JVM_WEEKLY_INTERNAL_API_TOKEN_SECRET="${JVM_WEEKLY_INTERNAL_API_TOKEN_SECRET:-}"

if [[ -z "$PROJECT_ID" ]]; then
  echo "[deploy-bff] FIREBASE_PROJECT_ID or GOOGLE_CLOUD_PROJECT is required"
  exit 1
fi

IMAGE_URI="gcr.io/${PROJECT_ID}/${SERVICE_NAME}:${IMAGE_TAG}"
NETWORK_ARGS=()
if [[ -n "$BFF_SERVERLESS_VPC_CONNECTOR" ]]; then
  NETWORK_ARGS+=(--vpc-connector "$BFF_SERVERLESS_VPC_CONNECTOR" --vpc-egress all-traffic)
fi
ENV_VARS="BFF_DEPLOY_ENV=${BFF_DEPLOY_ENV},FIREBASE_PROJECT_ID=${PROJECT_ID},BFF_ALLOWED_ORIGINS=${BFF_ALLOWED_ORIGINS},BFF_WORKERS_ENABLED=${BFF_WORKERS_ENABLED},BFF_SCHEDULER_OWNER=${BFF_SCHEDULER_OWNER},BFF_OUTBOX_BATCH=${BFF_OUTBOX_BATCH},BFF_OUTBOX_MAX_ATTEMPTS=${BFF_OUTBOX_MAX_ATTEMPTS},PII_MODE=${PII_MODE},PII_KMS_KEYS=${PII_KMS_KEYS},PII_KMS_CURRENT_KEY=${PII_KMS_CURRENT_KEY}"
if [[ -n "$JVM_WEEKLY_API_BASE_URL" ]]; then
  ENV_VARS="${ENV_VARS},JVM_WEEKLY_API_BASE_URL=${JVM_WEEKLY_API_BASE_URL}"
fi
if [[ -n "$JVM_WEEKLY_API_ID_TOKEN_AUDIENCE" ]]; then
  ENV_VARS="${ENV_VARS},JVM_WEEKLY_API_ID_TOKEN_AUDIENCE=${JVM_WEEKLY_API_ID_TOKEN_AUDIENCE}"
fi
SECRET_ARGS=()
if [[ -n "$JVM_WEEKLY_INTERNAL_API_TOKEN_SECRET" ]]; then
  SECRET_ARGS=(--set-secrets "JVM_WEEKLY_INTERNAL_API_TOKEN=${JVM_WEEKLY_INTERNAL_API_TOKEN_SECRET}:latest")
fi

echo "[deploy-bff] project=${PROJECT_ID} region=${REGION} service=${SERVICE_NAME} image=${IMAGE_URI}"

docker build -f server/bff/Dockerfile -t "$IMAGE_URI" .
docker push "$IMAGE_URI"

gcloud run deploy "$SERVICE_NAME" \
  --image "$IMAGE_URI" \
  --region "$REGION" \
  --platform managed \
  --allow-unauthenticated \
  "${NETWORK_ARGS[@]}" \
  --set-env-vars "$ENV_VARS" \
  "${SECRET_ARGS[@]}"

echo "[deploy-bff] done"
